export { default as Navbar } from "./Navbar/Navbar";
export { default as Hero } from "./Hero/Hero";
export { default as Statistics } from "./Statistics/Statistics";
export { default as Goals } from "./Goals/Goals";
export { default as Organizers } from "./Organizers/Organizers";
export { default as PrizeFund } from "./PrizeFund/PrizeFund";
export { default as Carousel } from "./Carousel/Carousel";
export { default as Winners } from "./Winners/Winners";
export { default as Gallery } from "./Gallery/Gallery";
